plugins {
    id "java-library"
    id "idea"
    id "maven-publish"
    id "net.neoforged.moddev" version "2.0.80"
}

version = "${project.mc_version}-${project.mod_version}"
group = "com.teamabnormals"

base {
    archivesName = project.mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neoforge
    parchment {
        minecraftVersion = project.mc_version
        mappingsVersion = project.parchment
    }

    runs {
        configureEach {
            systemProperty "forge.logging.markers", "REGISTRIES"
            systemProperty "forge.logging.console.level", "debug"
            systemProperty "blueprint.indev", "true"
        }

        client {
            client()
        }

        server {
            server()
        }

        data {
            data()
            programArguments.addAll "--mod", project.mod_id, "--all", "--output", file("src/generated/resources/").getAbsolutePath(), "--existing", file("src/main/resources/").getAbsolutePath()
        }

        dataTest {
            data()
            programArguments.addAll "--mod", "blueprint_test", "--all", "--output", file("src/generated_test/resources/").getAbsolutePath(), "--existing", file("src/test/resources/").getAbsolutePath()
        }
    }

    mods {
        "blueprint" {sourceSet(sourceSets.main)}
        "blueprint_test" {sourceSet(sourceSets.test)}
    }
}

sourceSets {
    test {
        compileClasspath += sourceSets.main.output + configurations.compileClasspath
        runtimeClasspath += sourceSets.main.output + configurations.runtimeClasspath
    }
}

sourceSets.main.resources {
    srcDir "src/generated/resources"
}

sourceSets.test.resources {
    srcDir "src/generated_test/resources"
}

dependencies {
}

tasks.named("jar", Jar).configure {
    manifest {
        attributes([
                "Specification-Title"     : project.mod_name,
                "Specification-Vendor"    : "Team Abnormals",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.mod_name,
                "Implementation-Version"  : project.mod_version,
                "Implementation-Vendor"   : "Team Abnormals",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.named("test").configure {
    enabled = false
}

task sourcesJar(type: Jar) {
    duplicatesStrategy(DuplicatesStrategy.FAIL)
    archiveClassifier.set("sources")
    from sourceSets.main.allJava
}

artifacts {
    archives sourcesJar
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [mod_version: mod_version, mc_version: mc_version, neoforge: neoforge]
    inputs.properties replaceProperties
    filesMatching(["META-INF/neoforge.mods.toml"]) {
        expand replaceProperties
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            artifact jar
            artifact sourcesJar
        }
    }
    repositories {
        maven {
            name = "abnormals"
            url = "https://maven.teamabnormals.com"
            credentials(PasswordCredentials)
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}